language: python
python:
  - "3.3"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - mkdir /tmp/build
  - sphinx-build . /tmp/build

after_success:
  - echo "${SSH_PRIV_KEY}" | base64 --decode >/tmp/sftp_rsa
  - echo "put -r /tmp/build /" > /tmp/batchfile
  - sftp -v -oIdentityFile=/tmp/sftp_rsa ${SSH_USER_NAME}@${SSH_DEPLOY_HOST} -b /tmp/batchfile
