language: python
python:
  - "3.3"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - mkdir /tmp/build
  - sphinx-build . /tmp/build

after_success:
  - echo "${SSH_PRIV_KEY}" | base64 --decode >/tmp/sftp_rsa
  - echo "rm -r /" > /tmp/batchfile
  - find /tmp/build -type d -exec echo mkdir {} \;|sed -e "s/build\///g" >> /tmp/batchfile
  - find /tmp/build -type f -exec echo put {} {} \;|sed -e "s/build\///g" >> /tmp/batchfile
  - sftp -b /tmp/batchfile -v -oIdentityFile=/tmp/sftp_rsa ${SSH_USER_NAME}@${SSH_DEPLOY_HOST}
